<a href="https://colab.research.google.com/github/iypc-team/Swift/blob/master/Python_Integration_swift.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import Foundation
import TensorFlow
import Python

%include "EnableIPythonDisplay.swift"
let plt = Python.import("matplotlib.pyplot")
let np = Python.import("numpy")



var zerosArray = np.zeros([4, 4])
var onesArray = np.ones([4, 4])
var vector = np.zeros([1,4])
vector += np.pi

zerosArray += (np.pi * 2)
print("onesArray", onesArray)
onesArray *= vector

print("vector:", vector)
//. print(zerosArray)
print("onesArray * vector", onesArray)
print(zerosArray*=onesArray)


onesArray [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
vector: [[3.14159265 3.14159265 3.14159265 3.14159265]]
onesArray * vector [[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]
()


In [0]:
import Foundation
import FoundationNetworking
import Dispatch

let 😎 = Double.pi
print(😎)
let cos = Foundation.tanh(😎)
print(cos)
